### ISSUE TITLE
Update Helm Chart

### ISSUE THREAD

**Issue by mprechtl** [ecsec/eidas-node-docker#23]
Helm chart must be updated, especially after the update to eIDAS-Node 2.7. We should also update the helm chart that all property keys can be set as values. Those values will then be set as entries in the specific property files.

For example (values.yaml):

```yaml
connector:
  metadata:
    url: https://eidas-node/eidas-node/metadata
```

becomes in the XML (eidas.xml) the following:

```
<entry key="connector.metadata.url">https://eidas-node/eidas-node/metadata</entry>
```
